"""add email_verified to users

Revision ID: 1eda2896ca82
Revises: 2c6bb30986d2
Create Date: 2026-08-13 12:17:04.445278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eda2896ca82'
down_revision: Union[str, Sequence[str], None] = '2c6bb30986d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
