"""add submitted_by_user_id to contracts

Revision ID: 2c6bb30986d2
Revises: dd4543705cdd
Create Date: 2026-08-11 14:52:23.217982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6bb30986d2'
down_revision: Union[str, Sequence[str], None] = 'dd4543705cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('submitted_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_contracts_submitted_by_user_id_users',
        'contracts', 'users', ['submitted_by_user_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_contracts_submitted_by_user_id_users', 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'submitted_by_user_id')
    # ### end Alembic commands ###
