"""add unique constraint on reminders clause and threshold

Revision ID: 6985145b33d0
Revises: 619840863a07
Create Date: 2026-08-06 09:05:16.349798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6985145b33d0'
down_revision: Union[str, Sequence[str], None] = '619840863a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_reminder_clause_threshold', 'reminders', ['clause_id', 'threshold_days'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reminder_clause_threshold', 'reminders', type_='unique')
    # ### end Alembic commands ###
