"""initial schema

Revision ID: 95e51469c4a6
Revises: 
Create Date: 2026-07-30 10:35:33.284793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95e51469c4a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_api_key_hash'), 'tenants', ['api_key_hash'], unique=True)
    op.create_table('contracts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('file_ref', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'docx', name='filetype'), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='contractstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_tenant_id'), 'contracts', ['tenant_id'], unique=False)
    op.create_table('clauses',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('effective_date', 'renewal_date', 'notice_period', 'termination_clause', name='clausetype'), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('original_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source_text_span', sa.String(), nullable=False),
    sa.Column('is_corrected', sa.Boolean(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clauses_contract_id'), 'clauses', ['contract_id'], unique=False)
    op.create_table('parties',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_contract_id'), 'parties', ['contract_id'], unique=False)
    op.create_table('reminders',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('trigger_date', sa.Date(), nullable=False),
    sa.Column('threshold_days', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_clause_id'), 'reminders', ['clause_id'], unique=False)
    op.create_index(op.f('ix_reminders_contract_id'), 'reminders', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_contract_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_clause_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_parties_contract_id'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_clauses_contract_id'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_contracts_tenant_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_tenants_api_key_hash'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
