"""add notification_email to tenants

Revision ID: e91c7ed600c9
Revises: 3db38842cf01
Create Date: 2026-08-07 12:56:40.517102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91c7ed600c9'
down_revision: Union[str, Sequence[str], None] = '3db38842cf01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('notification_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'notification_email')
    # ### end Alembic commands ###
