"""add is_demo to tenants

Revision ID: f0762878f89b
Revises: 1eda2896ca82
Create Date: 2026-08-13 19:52:07.399113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0762878f89b'
down_revision: Union[str, Sequence[str], None] = '1eda2896ca82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('tenants', sa.Column('is_demo', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'is_demo')
    # ### end Alembic commands ###
